#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
ENDCOLOR="\e[0m"

system_type=$(uname -s)
if ! [[ "$system_type" = "Linux" ]]; then
    echo -e "${RED}This script must be run on Linux!${ENDCOLOR}" 1>&2
    exit 1
fi

echo
echo -e "${GREEN}Installing packages...${ENDCOLOR}"
echo

pkgs=(zsh curl git make zip unzip gcc ripgrep base-devel tmux fzf openssh openssh-client openssh-server bat tree neovim firefox)

# apt
if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get -y --ignore-missing install "${pkgs[@]}"

# pacman
elif command -v pacman >/dev/null 2>&1; then
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed "${pkgs[@]}"

    if ! command -v yay >/dev/null 2>&1; then
        echo -e "${GREEN}Installing yay...${ENDCOLOR}"
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si
    fi
fi

echo
echo -e "${GREEN}Installing starship...${ENDCOLOR}"
echo
curl -sS https://starship.rs/install.sh | sh

echo
echo -e "${GREEN}Installing Oh My Zsh and Powerlevel10k...${ENDCOLOR}"
echo

ZSH_PATH=$(which zsh)

if [[ $ZSH_PATH =~ "sbin" ]]; then
    ZSH_PATH="${ZSH_PATH//sbin/bin}"
    echo -e "${YELLOW}warning:${ENDCOLOR} zsh path includes 'sbin'. Trying to change shell to $ZSH_PATH..."
fi

chsh -s $ZSH_PATH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo
echo -e "${GREEN}Installing nvm...${ENDCOLOR}"
echo

PROFILE=/dev/null sh -c "$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh)"
