#!/usr/bin/env zsh

alias venv="source ./.venv/Scripts/activate"
alias gg="lazygit"
alias yadmauto="yadm add -u && yadm commit -m 'Auto commit' && yadm push"
alias ls='ls --color=tty --group-directories-first'
alias tree="tree -C"

if command -v batcat >/dev/null 2>&1; then
    alias bat="batcat"
fi
