#!/usr/bin/env zsh

addToPath() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$PATH:$1
    fi
}

addToPathFront() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$1:$PATH
    fi
}

tmux-sessionizer() {
    if [[ $# -eq 1 ]]; then
        selected=$1
    else
	dirs=($HOME/repos $HOME/projects)
        selected=$(find "${dirs[@]}" -mindepth 1 -maxdepth 1 -type d | fzf)
    fi

    if [[ -z $selected ]]; then
        return 0
    fi

    selected_name=$(basename "$selected" | tr . _)
    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -s $selected_name -c $selected
        return 0
    fi

    if ! tmux has-session -t=$selected_name 2> /dev/null; then
        tmux new-session -ds $selected_name -c $selected
    fi

    tmux switch-client -t $selected_name
}

venv() {
    if [[ ! -f ./.venv/Scripts/activate ]]; then
        echo "venv script not found. Use 'python -m venv .venv' to create new virtual environment!"
	exit 1
    fi

    source ./.venv/Scripts/activate
}
